### ISSUE TITLE
COMMAND NOT FOUND

### ISSUE THREAD

**Issue by Madriax** [dbohdan/csv2html#6]
Everything is said in the title.

**Comment by dbohdan** [comment]
>Everything is said in the title.

I can't agree with that.  Which command do you mean?  If you want help or would like to report a bug, please describe what you did and what happened.

**Comment by Madriax** [comment]
I did exactly the right things as it is described in the README

**Comment by dbohdan** [comment]
This is not enough information to debug your problem.  I need to know how you followed the installation instructions and what exactly went wrong.  Try installing again and paste the full terminal log here.  Include information about your computer's OS (which OS it is, the version, `uname -a` if it's *nix) and your `PATH` environment variable.

Unsolicited advice time.  Judging by your hovercard, you are studying software engineering or something related.  It will benefit you, those you work with, and your users if you learn how to better isolate and report technical problems now rather than later in your career.  A fairly good starting point could be [this StackOverflow question](https://stackoverflow.com/questions/240323/how-to-report-bugs-the-smart-way).
